### ISSUE TITLE
Plataforma não suportada. LINUX

### ISSUE THREAD

**Issue by eneiasramos** [marcosgerene/Gerene.DFe.EscPos#10]
Caros,

Quando tento rodar no ambiente LINUX recebo o seguinte erro:

Plataforma não suportada.

Sabem o que pode ser?

Obrigado!

**Comment by marcosgerene** [comment]
Pode ser mais especifico?

O demo foi feito em WinForms, logo somente windows, o componente em si deveria rodar em ambiente Linux.

Poste o StackTrace completo e informações do ambiente (como a distribuição).

**Comment by eneiasramos** [comment]
@marcosgerene falando com o desenvolvedor do OpenAC ele disse que se implementar o FileConfig pode funcionar:

https://github.com/OpenAC-Net/OpenAC.Net.EscPos/issues/9

**Comment by eneiasramos** [comment]
@marcosgerene segue um PR para vossa apreciação:

https://github.com/marcosgerene/Gerene.DFe.EscPos/pull/11

**Comment by eneiasramos** [comment]
@marcosgerene falou um detalhe meu caro: https://github.com/marcosgerene/Gerene.DFe.EscPos/pull/12

**Comment by eneiasramos** [comment]
@marcosgerene testado 2 cenários via FileConfig:

1 - Usando um arquivo temporario **/tmp/test** e depois utilizando o comando **lp** para imprimir o arquivo:

```c#
using (var _printer = new GereneDFeEscPos.NFCePrinter())
{
    _printer.TipoConexao = GereneDFeEscPos.TipoConexao.File;
    _printer.Impressora = "/tmp/test";
}
``` 

```shell
lp -d "EPSON-TM-T20X" /tmp/test
``` 

2 - Usando o diretamente o arquivo de dispositivo USB **/dev/usb/lp1** para imprimir o arquivo direto na impressora:

```c#
using (var _printer = new GereneDFeEscPos.NFCePrinter())
{
    _printer.TipoConexao = GereneDFeEscPos.TipoConexao.File;
    _printer.Impressora = "/dev/usb/lp1";
}
``` 

Porém neste caso é necessário dar permissão para o arquivo de dispositivo USB:

Permissão a nível de usuário:

```shell
sudo usermod -aG lp username
``` 

Permissão a nível root:

```shell
sudo chmod 777 /dev/usb/lp1
``` 

Em ambos os testes imprimiu perfeitamente.

O único ponto pendente é a questão da **codificação***:

![image](https://github.com/marcosgerene/Gerene.DFe.EscPos/assets/2862728/dc9078fe-10c3-4bf7-bf92-9a608b1423fc)

**Comment by rftd** [comment]
@eneiasramos usando o comando LP talvez de para fazer um workaround no RAW tbm, salvando de forma temporária e passando o comando.

**Comment by eneiasramos** [comment]
@rftd entendi! excelente dica meu caro! o/

**Comment by rftd** [comment]
Já fiz um modificações e mandei para o repositório Devices se puder dá uma testada depois
