### ISSUE TITLE
Exception ao inicializar a classe NFCePrinter()

### ISSUE THREAD

**Issue by dkraide** [marcosgerene/Gerene.DFe.EscPos#4]
Oi tudo bem ?? 
 Alguém poderia me ajudar a corrigir esse errinho ? 

![print1](https://user-images.githubusercontent.com/43674712/94343738-9b3e3280-fff0-11ea-87a2-0ed25fa90d59.png)

Acredito que o problema esteja na version da assembly que ta apontando outra numeração 
 Version=1.0.0.770 (esssa é a qual o zeus apresenta pra mim)
![print2](https://user-images.githubusercontent.com/43674712/94343739-9bd6c900-fff0-11ea-893a-d0d60c9110d8.png)

**Comment by marcosgerene** [comment]
@dkraide 

Isso acontece no Demo ou no seu projeto local?

Atualizou/restaurou os pacotes nuget antes de compilar?

**Comment by marcosgerene** [comment]
@dkraide

Tenho algumas questões:
   1. O projeto que usa essa biblioteca usa qual framework? (.Net Core, .Net Full, .Net Standard ...)
   2. Caso a resposta da primeira seja .Net Standard (projeto intermediario antes do final), defina o mesmo como multitarget, como fito em #3 .
   3. Chegou a testar com demo?

E algumas considerações:

Seu problema é sobre referência à biblioteca do Zeus, o projeto atende o .Net Standard 2.0 e .Net Framework 4.6.2. 

Para .Net Core, ou qualquer outro que use a opção .Net Standard, o projeto usa as bibliotecas do Zeus com final .Standard.dll.

Você pode até ver melhor aqui: ZeusAutomacao/DFe.NET#1113

---

Demo compilado em .Net Full
![image](https://user-images.githubusercontent.com/15945003/94345610-83b97680-fffd-11ea-9850-81638451e809.png)

Demo compilado em .Net Standard
![image](https://user-images.githubusercontent.com/15945003/94345617-92079280-fffd-11ea-96ae-04eb016a27f7.png)

**Comment by marcosgerene** [comment]
Alguma novidade?
