### ISSUE TITLE
Impressão CFe SAT MFe SEFAZ CE

### ISSUE THREAD

**Issue by khaddmussistemas** [marcosgerene/Gerene.DFe.EscPos#5]
Boa  noite, 
Amigo, quando eu imprimo um XML CFE MFE SEFAZ CE 
não aparece o QRCODE SABE ME DIZER PQ?

Grato pela ajuda e parabens pela ferramenta

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Por favor, anexe o XML, vou tentar imprimir na minha impressora aqui e testar.

Informe também qual a marca e modelo da impressora.

**Comment by khaddmussistemas** [comment]
A impressora que eu informo é a EPSON.

**Comment by marcosgerene** [comment]
Por favor, poste o modelo da impressora o xml do documento que esta imprimindo.

**Comment by khaddmussistemas** [comment]
Epson
Segue o xml em anexo.

Em sex, 6 de nov de 2020 13:03, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
Você não postou o xml.

A Epson tem mais de um modelo de impressora, me informe o modelo exato.

**Comment by khaddmussistemas** [comment]
no fonte eu coloco o epson mas minha impressora ´e um ITE-P80HBT PORTABLE
80MM
USEI NFCE E FUNCIONOU O QRCODE.

Grato.

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Ok, não entendi muita coisa, mas se deu certo ótimo... 

Valeu

**Comment by khaddmussistemas** [comment]
Nao nfce da certo
Mas esse xml que te mandei não dá

Em sex, 6 de nov de 2020 15:53, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
Amigo, voce nao mandou o Xml

**Comment by khaddmussistemas** [comment]
Pode me passar seu zap para eu te explicar melhor?

Em sex, 6 de nov de 2020 16:37, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Não ofereço suporte direto, somente ajudo em issues. Por favor poste o XML pelo github ao invés de responder por e-mail, assim consigo tentar entender seu problema.

**Comment by khaddmussistemas** [comment]
Deixa eu te mandar aqui em anexo  está em anexo o xml.
Esse xml e de um cupom fiscal eletrônico aqui do Ceará . Aqui a gente usa o
SAt igual de São Paulo.
A impressão não sai o qrcode.
Eu debuguei seu código mas não consigo achar o problema.
Grato por sua gentileza.



Em sex, 6 de nov de 2020 16:55, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Eu conheço o MFe, tenho alguns clientes no CE.

Como eu disse, não está anexando, por favor, anexe direto no github, não no e-mail

**Comment by khaddmussistemas** [comment]
Olá segue o xml em anexo.
[cfe.zip](https://github.com/marcosgerene/Gerene.DFe.EscPos/files/5504010/cfe.zip)
Pronto

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Vou testar com a minha impressora na segunda-feira e te dou um feedback.

**Comment by khaddmussistemas** [comment]
Muito obg

Em sáb, 7 de nov de 2020 09:25, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Tenho uma Epson Tm-20 e uma Elgin i9 para testes, tive sucesso em ambos os casos.

Testei a impressão 80 e 58mm, com o Vip.Printer na versão 1.0.20.

Acredito que seja algo relacionado à sua impressora. Se for o caso, acredito que a sua issue deve ser direcionada à fabricante ou ao projeto que uso como motor de impressão aqui (Vip.Printer), esse projeto em questão é só uma "ligação" entre o Vip.Printer e os projetos ACBr.Sat e o DFe.Net.

**Comment by leandrovip** [comment]
Boa noite! Tomei a liberdade de testar aqui nas impressoras que tenho (Dual Print DIMEP, Bematech 2500, Tanca 650) em todas foi impresso corretamente. Muito provavelmente, se não der certo, deve ser relacionado ao set de comandos da impressora. Verifique se está como ESCPOS e se tem algum outro tipo de configuração na impressora!

[]´s

**Comment by khaddmussistemas** [comment]
Muito obg pelas informações eu vou testar sim a minha é aquelas mini
impressora da china ,
