### ISSUE TITLE
'IBM860' is not a supported encoding name

### ISSUE THREAD

**Issue by nielson266** [marcosgerene/Gerene.DFe.EscPos#6]
Boa Tarde Baixei pelo nuget e fiz tentei fazer a impressão seguindo o exemplo e não deu certo, deu esse erro - : 'IBM860' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. 

Baixei o exemplo modelo, imprimiu peguei a dll do escpos e a versao vip,print final 19, mais ainda da o mesmo erro.

**Comment by marcosgerene** [comment]
@nielson266 

Boa noite,

Pode postar o xml e o trecho da seu código aonde chama a impressão para eu testar aqui?

Acredito  que o problema está na deserealização do xml.

**Comment by nielson266** [comment]
Segue o arquivo xml. 
Obrigado pela atenção!
[xmlNovo.zip](https://github.com/marcosgerene/Gerene.DFe.EscPos/files/5745515/xmlNovo.zip)

**Comment by leandrovip** [comment]
Bom dia! 

Qual o modelo de impressora utilizada?

**Comment by marcosgerene** [comment]
@leandrovip 

>Baixei o exemplo modelo, imprimiu peguei a dll do escpos e a versao vip,print final 19, mais ainda da o mesmo erro.

A pontuação (falta dela rs) fez o texto ficar ambíguo, mas acredito que o demo funcionou, então acho que não é a impressora o problema. De qualquer forma vou testar o xml dele numa Tm-20 aqui.

**Comment by nielson266** [comment]
Impressora jetway jp-800

**Comment by marcosgerene** [comment]
@nielson266 

Acabei de mandar um commit de uma falha que peguei com esse xml seu. 
Por favor, baixe o fonte e testa com o Demo.

**Comment by nielson266** [comment]
@marcosgerene com a demo peguei esse erro tb só que comentei e imprimiu, foi nas obs do fisco, foi esse mesmo erro?

**Comment by marcosgerene** [comment]
@nielson266 
>  foi nas obs do fisco, foi esse mesmo erro?

Sim, corrigi

**Comment by nielson266** [comment]
O meu projeto estou usando core3.1, será que tem algum problema?

**Comment by marcosgerene** [comment]
>O meu projeto estou usando core3.1, será que tem algum problema?
Não, o demo .NetCore usa a mesma versão

**Comment by nielson266** [comment]
Vou testar a demo, nuget vai subir depois?

**Comment by marcosgerene** [comment]
@nielson266 
Já subi, ele demora um pouco para publicar.

**Comment by nielson266** [comment]
![escpos](https://user-images.githubusercontent.com/2091005/103223366-d52b1780-4904-11eb-967c-4bad53de9631.png)
@marcosgerene 'IBM860' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name').
No emulador passa mais no meu projeto não passa, peguei as dll e importei e nada.

**Comment by marcosgerene** [comment]
@nielson266 
O erro estoura na linha "Imprimir"?

Se funciona no demo e não funciona no seu projeto pode ser algo específico do seu projeto... Faça o seguinte teste: crie um projeto novo do zero (pode ser net core ou framework, o que for melhor pra voce) e jogue exatamente o mesmo código e a mesma dll e veja se funciona.

Se funcionar, isolamos o erro, é algo na aplicação. Se não funcionar farei o mesmo aqui para testar.

**Comment by marcosgerene** [comment]
Fechado por falta de resposta, mesmo problema reportado em #7 acompanhe lá o desfeixo.
