### ISSUE TITLE
Erro 'IBM860' 

### ISSUE THREAD

**Issue by khaddmussistemas** [marcosgerene/Gerene.DFe.EscPos#7]
Bom dia !
Guerreiros! 
Estou com esse erro ao imprimir um CFe SAT MFE CE . 
'IBM860' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name').
O Erro ocorre no .Imprimir(XML)
Segue o xml e a imagem do codigo.
Grato.

[CFe35210108723218000186599000192000001910372615.zip](https://github.com/marcosgerene/Gerene.DFe.EscPos/files/5787380/CFe35210108723218000186599000192000001910372615.zip)

![image](https://user-images.githubusercontent.com/71778467/104019439-5357ab80-519a-11eb-8d4d-bba31803aaa7.png)

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Não estou no escritório agora, chegando eu testo seu  XML, mas faz um teste passando ```null``` no LOGOTIPO.

**Comment by khaddmussistemas** [comment]
Já fiz isso e está dando o mesmo erro.
Agradeço sua ajuda;

Em sex., 8 de jan. de 2021 às 12:30, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
@khaddmussistemas  O erro não ocorre aqui com seu XML.

Teste com o demo foi sucesso, configurei igual seu print.

Por favor, baixe este fonte, compile e referencie a DLL ao invés de usar o nuget. Faça o erro ocorrer e poste o StackTrace do erro, quero entender em que momento dentro do imprimir ele ocorre.

**Comment by khaddmussistemas** [comment]
Estanho está dando erro na linha 77 da classe SatPrinter , sendo que tem
nome fantasia no XML
[image: image.png]

Em sex., 8 de jan. de 2021 às 13:57, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Sua imagem não foi carregada....

**Comment by marcosgerene** [comment]
Estou fechando por falta de respostas

**Comment by marcosgerene** [comment]
Estou fechando por falta de resposta, se o problema persistir reabra a issue.

**Comment by leandrovip** [comment]
Saudaçoes,

Recentemente tive este mesmo erro em um projeto .Net5.
Vou deixar registrado aqui como resolvi o problema para futuras consultas:

Na inicialização do projeto (classe Program/Main por exemplo), inclui o seguinte código:

```csharp
var encodings = System.Text.CodePagesEncodingProvider.Instance;
Encoding.RegisterProvider(encodings );
```
[]´s
