### ISSUE TITLE
Problema impressao MP-4200 TH

### ISSUE THREAD

**Issue by lkfischer** [marcosgerene/Gerene.DFe.EscPos#8]
Boa tarde, estou tentando imprimir uma nota da impressora da Bematech, infelizmente ela esta saindo da forma como na foto em anexo, mesmo eu setando a "PrinterType", alguem sabe o motivo.

Obrigado mesmo assim.

![WhatsApp Image 2021-01-19 at 18 22 10](https://user-images.githubusercontent.com/17318400/105096015-3d44c780-5a85-11eb-8b59-8c531b6391d6.jpeg)

**Comment by marcosgerene** [comment]
@lkfischer 

A MP-4200-TH é complicada... driver dela é chatíssimo de funcionar... tem uma atualização dela de firmware se não me engano que faz funcionar via EscPos também, ou seja, não precisa setar como BemaPos.

Use o demo do Vip.Printer para testar se a impressora está recebendo comandos do tipo EscPos ou BemaPos e teste em um PC com Windows 7 "limpo" só para ver a questão do driver.

Tive um problema parecido e só formatando o PC consegui resolver.

**Comment by lkfischer** [comment]
@marcosgerene , isso e um problema de driver?

**Comment by marcosgerene** [comment]
@lkfischer No meu caso, era, mas isso faz um bom tempo e esse projeto aqui nem existia.

Testa com o demo do Vip.Printer, lá diz que esse modelo foi testado e é compatível. Como aquele projeto é o motor de impressão deste, então o que funcionar lá funciona aqui.

**Comment by lkfischer** [comment]
Bom dia @leandrovip e @marcosgerene , fiquei ausente pois eu na minha cidade foi feriado e nao consegui entrar, mas entao eu configurei a mesma em ESCPOS e mesmo assim continua quebrando, eu tenho uma ELGIN i9 e aquelas 80mm genericas ESCPOS e nao tenho nenhum problema quanto a impressao. Entretanto com essa Bematech esta complicada.

Segue foto abaixo da da configuração da impressora e a versao do firmware atrás da para verificar como esta saindo a impressão em ESCPOS e veja que nem o QRCode sai:

![WhatsApp Image 2021-01-22 at 10 13 42](https://user-images.githubusercontent.com/17318400/105496086-c3d2f200-5c9b-11eb-9ae5-4721c84d7fac.jpeg)

**Comment by lkfischer** [comment]
@leandrovip fiz o teste com seu VIP Printer
![WhatsApp Image 2021-01-22 at 10 54 09](https://user-images.githubusercontent.com/17318400/105499772-b4a27300-5ca0-11eb-9911-49d8ee291eb6.jpeg)

Mesma coisa.

**Comment by marcosgerene** [comment]
@lkfischer 

> @leandrovip fiz o teste com seu VIP Printer

No teste com o VipPrinter aonde ele aponta 48 colunas deveria sair tudo na mesma linha, bonitinho, ou seja, tem algo errado ai também.

Bem, vou deixar a issue aqui aberta porque o @leandrovip está acompanhando, mas neste caso é algo relacionado ao motor de impressão e não à este projeto em si.

**Comment by lkfischer** [comment]
Realmente, deve ser, acabei de testar em uma outra impressora 4200 TH e ta a mesma coisa.

**Comment by lkfischer** [comment]
@marcosgerene  e @leandrovip , consegui imprimir, eu tive que colocar ela no modo ESCBEMA e na sua biblioteca @marcosgerene mudar para imprimir em ESCPOS, fiz o mesmo teste no VIP e tive que realizar o mesmo procedimento.

**Comment by marcosgerene** [comment]
@lkfischer show de bola, vou esperar um feedback do @leandrovip e fechar a issue em seguida, obrigado!

**Comment by leandrovip** [comment]
Bom dia senhores, 
Desculpe a demora, estava viajando.
A MP4200, pelos testes que fiz, o QRCODE só imprime com sucesso via set (= conjunto de comandos) ESCBEMA, no set ESCPOS não é para todas utilizado o comando 'universal', então para bematech (MP4200, MP2500) sempre aconselho a usar o ESCBEMA que não tem erro. 
O último firmware da 4200 é o 1.7 (pelo menos o que tenho aqui), então caso necessário pode-se atualizar também.

Com o conjunto de comandos ESCBEMA selecionado na impressora, no Vip.Printer utilize o PrinterType Bematech que é sucesso.
Qualquer coisa que eu possa ajudar, estou à disposição

[]s

**Comment by lkfischer** [comment]
@leandrovip , so para deixar de registro essa configuracao que eu fiz foi no firmware 1.22 da Bematech MP-4200 TH, sendo a ultima versao disponivel no site deles. Obrigado pelo suporte dos dois.

Abracos e se puder ajudar tamo ae.

**Comment by thiagovalim** [comment]
@leandrovip você tem o link de download do firmeware 1,7? No site deles só tem até a versão 1.22

**Comment by leandrovip** [comment]
@thiagovalim,

Segue anexo..

[MP_4200_TH_v1_7.zip](https://github.com/marcosgerene/Gerene.DFe.EscPos/files/5933157/MP_4200_TH_v1_7.zip)
